export const NAMES = [
  'Charlotte',
  'Reuben',
  'Milo',
  'Josh',
  'Jess',
  'Benny',
  'A Beagle',
  'Master Chief',
  'Beef Boss',
  'Papa Luigi',
  'Dr. John',
  'Cayetano',
  'Taco El Lago',
  'Finn',
  'Mebaa',
  'Clara',
  "Ma'ano",
  'Monster Hunter',
  'Garlic Crush',
  'The White Fluffy Dog Down The Street',
  'Mid-Field Crisis',
  'Domino',
  'Captain Kirk'
]

export const NOUNS = [
  'Snack Overflow',
  'Beagle',
  'ACL',
  'Boba Tea',
  'Frog Toy',
  'NYT Mini Crossword', 
  'Knit Night',
  'Trivia Night',
  'Hot Tub Boats',
  'Pickleball Paddle',
  'Antler',
  'Cottage Cheese On Pickles',
  'Bouldering Project',
  'Thin Crust Pepperoni Pizza',
  'Pacific Rim',
  'Puppuccino',
  'Fried Chicken Sandwich',
  'Chili',
  'Chesting Of The Ball',
  'Knitting Needle',
  '3 Body Problem',
  'Baked Goods',
  'Brightcore',
  'Brewing Company'
]
